#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
runcmd:
  - [ bash, -lc, "usermod -aG docker azureuser" ]
  - [ bash, -lc, "mkdir -p /home/azureuser/project/monitoring" ]