---
- name: Diagnose and remediate nginx-demo container
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check nginx container status
      command: docker inspect -f '{{'{{.State.Running}}'}}' nginx-demo
      register: nginx_inspect
      failed_when: false
      changed_when: false

    - name: Restart nginx container if not running
      command: docker restart nginx-demo
      when: nginx_inspect.rc != 0 or nginx_inspect.stdout != "true"
